[package]
name = "mca-parser"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
license-file = "LICENSE"
homepage = "https://github.com/funnyboy-roks/mca-parser"
repository = "https://github.com/funnyboy-roks/mca-parser"
description = "A simple library for parsing Minecraft's .mca format"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
